### ISSUE TITLE
diff two array tests enforces sorting

### ISSUE THREAD

**Issue by EirikAskheim** [3rfaan/rust_algorithms#1]
src/exercises/diff_two_arrays.rs
```
#[allow(dead_code)]
#[allow(unused_variables)]
fn diff_array<'a>(arr1: Vec<&'a str>, arr2: Vec<&'a str>) -> Vec<&'a str> {
    arr1.iter()
        .chain(arr2.iter())
        .filter(|x| !arr1.contains(x) | !arr2.contains(x))
        .map(|x| *x)
        .collect()
}
```

This solution fails test2 because it returns a different sorting order than expected. The description says the vec returned can be in any order.

**Comment by EirikAskheim** [comment]
I believe this should fix the test to be in line with the problem description.
https://github.com/3rfaan/rust_algorithms/pull/2

**Comment by 3rfaan** [comment]
Thanks!
